//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_drp : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 trackpadPosition
        {
            get
            {
                return SteamVR_Actions.drp_trackpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean trackpadTouch
        {
            get
            {
                return SteamVR_Actions.drp_trackpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean trackpadClick
        {
            get
            {
                return SteamVR_Actions.drp_trackpadClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean menu
        {
            get
            {
                return SteamVR_Actions.drp_menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean grip
        {
            get
            {
                return SteamVR_Actions.drp_grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean system
        {
            get
            {
                return SteamVR_Actions.drp_system;
            }
        }
        
        public virtual SteamVR_Action_Boolean triggerClick
        {
            get
            {
                return SteamVR_Actions.drp_triggerClick;
            }
        }
        
        public virtual SteamVR_Action_Single triggerPull
        {
            get
            {
                return SteamVR_Actions.drp_triggerPull;
            }
        }
    }
}
